title: "Data Analytics Portfolio"
description: "Cyclistic bike-share case study and other analytics projects."
theme: minima

author:
  name: "dpf-tech"

baseurl: "/cyclistic-case-study"
url: "https://dpf-tech.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
